# ----------------------------------------------------------------------------
#
# Package             : spring-framework
# Source Repo         : https://github.com/spring-projects/spring-framework
# Travis Job Link     : https://travis-ci.com/github/asellappen/spring-framework/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
dist: focal

language: java

jdk:
   - openjdk11
os:
  - linux
arch:
  - amd64
  - ppc64le
script :
    #- travis_wait 15 ./gradlew build
    #- travis_wait 15 ./gradlew clean test
    #- ./gradlew intTest
    - sh -x ci/scripts/build-project.sh
    - sh -x ci/scripts/check-project.sh
