# ----------------------------------------------------------------------------
#
# Package             : spring-framework
# Source Repo         : https://github.com/spring-projects/spring-framework
# Travis Job Link     : https://travis-ci.com/github/asellappen/spring-framework/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: java

jdk:
   - openjdk9
os:
  - linux
arch:
  - amd64
  - ppc64le
script :
    - ./gradlew build --warning-mode all
    - ./gradlew -a :spring-webmvc:test
    - ./gradlew clean test
    

